# Generated by Django 4.2.16 on 2024-12-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_admission_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='Phone_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
