# Generated by Django 4.2.16 on 2024-12-10 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_contactus_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
