# Generated by Django 4.2.16 on 2024-12-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_admission_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='address',
            field=models.CharField(default=1, max_length=255, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admission',
            name='college_name',
            field=models.CharField(default=1, max_length=150, verbose_name='College Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admission',
            name='passed_out',
            field=models.BooleanField(default=False, verbose_name='Passed Out'),
        ),
        migrations.AddField(
            model_name='admission',
            name='passed_out_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Passed Out Year'),
        ),
        migrations.AddField(
            model_name='admission',
            name='qualification',
            field=models.CharField(default=1, max_length=150, verbose_name='Qualification'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admission',
            name='course',
            field=models.CharField(choices=[('programming', 'Programming'), ('web_development', 'Web Development'), ('cad', 'Civil CAD'), ('other', 'Other Programs')], max_length=50, verbose_name='Selected Course'),
        ),
    ]
