# Generated by Django 4.2.16 on 2024-12-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_admission_address_admission_college_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='course',
            field=models.CharField(choices=[('programming', 'Programming'), ('web_development', 'Web Development'), ('data_science', 'Data Science'), ('machine_learning', 'Machine Learning'), ('cloud_computing', 'Cloud Computing'), ('cyber_security', 'Cyber Security'), ('game_development', 'Game Development'), ('civil_cad', 'Civil CAD'), ('mechanical_cad', 'Mechanical CAD'), ('digital_marketing', 'Digital Marketing'), ('graphic_design', 'Graphic Design'), ('other', 'Other Programs')], max_length=50, verbose_name='Selected Course'),
        ),
    ]
