# Generated by Django 4.2.16 on 2025-01-08 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
