# Generated by Django 4.2.16 on 2025-01-11 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Created By User ID'),
        ),
        migrations.AddField(
            model_name='admission',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date'),
        ),
        migrations.AddField(
            model_name='admission',
            name='modified_by_user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Modified By User ID'),
        ),
        migrations.AddField(
            model_name='admission',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Date'),
        ),
        migrations.AddField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
