# Generated by Django 4.2.16 on 2025-01-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_delete_course_alter_admission_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
    ]
