# Generated by Django 4.2.16 on 2025-01-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_rename_email_contactus_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='message',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='phone_number',
            new_name='Phone_number',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='previous_methodology',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Finished', 'Finished')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='contactus',
            name='Full_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
