# Generated by Django 4.2.16 on 2025-01-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_alter_admission_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='course',
            field=models.CharField(choices=[('C_programming', 'C Programming'), ('Python_programming', 'Python Programming'), ('J_programming', 'Java Programming'), ('R_js', 'React JS'), ('F_dev', 'Front End Development'), ('web_development', 'Full Stack Web Development'), ('civil_cad', 'Civil CAD'), ('mechanical_cad', 'Mechanical CAD'), ('digital_marketing', 'Digital Marketing'), ('graphic_design', 'Graphic Design'), ('other', 'Other Programs')], max_length=50, verbose_name='Selected Course'),
        ),
    ]
