# Generated by Django 4.2.16 on 2025-01-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_contactus_modified_date_contactus_submission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('on_progress', 'On Progress'), ('finished', 'Finished')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
