# Generated by Django 4.2.16 on 2025-01-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_contactus_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='course',
            field=models.CharField(choices=[('C_programming', 'C Programming'), ('Python_programming', 'Python Programming'), ('Java_programming', 'Java Programming'), ('R_js', 'React JS'), ('F_dev', 'Front End Development'), ('Web_development', 'Full Stack Web Development'), ('Civil_cad', 'Civil CAD'), ('Mechanical_cad', 'Mechanical CAD'), ('Digital_marketing', 'Digital Marketing'), ('Graphic_design', 'Graphic Design'), ('other', 'Other Programs')], max_length=50, verbose_name='Selected Course'),
        ),
    ]
