# Generated by Django 4.2.16 on 2025-01-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_alter_admission_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='subject',
        ),
        migrations.AlterField(
            model_name='admission',
            name='course',
            field=models.CharField(choices=[('C_programming', 'C Programming'), ('Python_programming', 'Python Programming'), ('Java_programming', 'Java Programming'), ('React_js', 'React JS'), ('Front_end_development', 'Front End Development'), ('Web_development', 'Full Stack Web Development'), ('Civil_cad', 'Civil CAD'), ('Mechanical_cad', 'Mechanical CAD'), ('Digital_marketing', 'Digital Marketing'), ('Graphic_design', 'Graphic Design'), ('Other', 'Other Programs')], max_length=50, verbose_name='Selected Course'),
        ),
    ]
