# Generated by Django 4.2.16 on 2024-12-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
